### ISSUE TITLE
MS Visual Studio 2019 reports missing include of stdexcept in docopt_value.h

### ISSUE THREAD

**Issue by Thomas-Haase** [docopt/docopt.cpp#108]
The code does not compile with MS Visual Studio Professional 2019 Preview (Version 16.0.0 Preview 4.2). It reports missing include of stdexcept in docopt_value.h.

**Comment by rdeterre** [comment]
If I'm not mistaken, this could be closed now, the problem is fixed in master

**Comment by jaredgrubb** [comment]
Indeed! Thanks for that notice :) @Thomas-Haase please let me know if your issue is not actually resolved.

**Comment by Thomas-Haase** [comment]
Thanks. Yes, the issue is resolved.
