### ISSUE TITLE
why is docopt_value kind private?

### ISSUE THREAD

**Issue by drtconway** [docopt/docopt.cpp#115]
Hi docopt.cpp,

Great work, thank you!

Is there a particular rationale for making the kind of a docopt_value private?

I use a command/factory paradigm internally, and want to convert the command line into a jsonish blob to pass to the create method, and allow it to be saved/composed/etc. With the interface as it is, I either have to write the translation explicitly in each sub-command, or I could write a converter which uses try/catch to catch the runtime_error exceptions.

If you think exposing a "Kind kind() const" sort of thing is acceptable, I'm happy to do the implementation and submit a pull request, but if there's a specific reason not to, then I won't bother.

Cheers,
Tom.

**Comment by jaredgrubb** [comment]
I can't think of a good reason it must be private. I think my thought was "you wrote the docopt string, so you probably already know the types that should be there" ... but if someone finds the enum useful, it's not harmful to expose it. (Although in a better work

**Comment by jaredgrubb** [comment]
Sorry didn't mean to close this. Open for patch!

**Comment by Kerndog73** [comment]
PR #126 was merged. This issue can be closed.

**Comment by jaredgrubb** [comment]
Thanks!
