### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tdegeus** [docopt/docopt.cpp#116]
I would like to add `docopt.cpp` to [conda-forge](https://conda-forge.org). However, it relies on releases. Therefore it would be great of a new release can be made! 

Once this is done, I can create the conda-forge package. It would be great if I can add one or more of the authors/maintainers to that package, for them to have push-rights also for the conda-forge package.

**Comment by tdegeus** [comment]
The conda-forge recipe is live:

https://github.com/conda-forge/docopt.cpp-feedstock

The invitation to authors/maintainers/contributors to become a maintainer to the conda-forge package is still open !

**Comment by jaredgrubb** [comment]
There's not much in the latest patches. We could spin a release though. Maybe after the weekend and I can get these patches curated :)

**Comment by tdegeus** [comment]
It's true that the number of patches is limited. So no big hurry!

**Comment by tdegeus** [comment]
Also, a thing to consider is the following, which I recently came across on fmt

https://github.com/fmtlib/fmt/pull/1437
https://github.com/conda-forge/fmt-feedstock/issues/5

**Comment by tdegeus** [comment]
@jaredgrubb Are you interested in being a co-maintainer of https://github.com/conda-forge/docopt.cpp-feedstock ? It would not require anything of you, but you would have push-rights just in case. 

It could be nice to understand https://github.com/docopt/docopt.cpp/issues/124 before releasing. That would make sure that the updated conda-forge feedstock does not contain the problem, whatever it may be...

**Comment by jaredgrubb** [comment]
I'm open to that. Not sure what I would do with it, but happy to do it if it helps.

**Comment by chrisdembia** [comment]
A new release would be great. I think the commits since 0.6.2 are quite substantial (build system improvements).

**Comment by jaredgrubb** [comment]
Tagged and  released!

**Comment by tdegeus** [comment]
Great! The new version is also live on conda-forge.

**Comment by chrisdembia** [comment]
Yay!

**Comment by jaredgrubb** [comment]
Awesome thanks!

**Comment by chrisdembia** [comment]
I’ve already been able to incorporate this in my opensim stages recipe for conda forge. 👍
