### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by tdegeus** [docopt/docopt.cpp#119]
It seems that currently the CI is failing unrelatedly to PRs

**Comment by jaredgrubb** [comment]
Fixed the OS X issues ... still struggling to get the Linux+boost::regex build to work right.

**Comment by jaredgrubb** [comment]
Mind taking a look at the #121  fix? 

Issue appears to be that the compilers used were all pretty old and the boost::regex test was with gcc-4.8, which was just prior to a major ABI change in gcc-5. So I think the linker issues were that the pre-installed boost::regex was linked against libstdc++-5 but then docopt was built using libstdc++4.8, and that caused the ABI problem in the linker.

I've just cleaned out all those old GCC and Clang versions, moving the boost test to g++-9.

**Comment by jaredgrubb** [comment]
Ok, the CI is all good now, yay :) Thanks for the prodding on this!

If anyone knows Travis better, or knows a C++ repo that has a good TravisCI file that we could emulate, please let me know!
