### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [docopt/docopt.cpp#15]
I would like to point out that an identifier like "[`__docopt__value__`](https://github.com/docopt/docopt.cpp/blob/ea3a2ee6fa83266b7f3a4791bafc90668baf4888/docopt_value.h#L9)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jaredgrubb** [comment]
Yes we should.

**Comment by jaredgrubb** [comment]
I have pushed a fix for this. Thanks for the report!

**Comment by elfring** [comment]
How do you think about to change also [any remaining double underscores in affected identifiers](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by jaredgrubb** [comment]
Are there still some?

**Comment by elfring** [comment]
Yes. - I find that [your fix was incomplete](https://github.com/docopt/docopt.cpp/commit/a6d4652730603015e646430c706b9a34d6bc0f53#diff-a896caa3d51f7b7a391c8fc68b3d5bcdR9 "Renaming of two include guards") a moment ago.

**Comment by jaredgrubb** [comment]
I did a grep for “__” in the sources and am unable to find anything left. Can you be more specific on what is still missing?

**Comment by elfring** [comment]
I suggest to drop another underscore from a prefix like "`docopt__`" for example.
