### ISSUE TITLE
Parser does not correctly identify option description if on new line

### ISSUE THREAD

**Issue by archshift** [docopt/docopt.cpp#31]
#### Example of what does not work:

```
Options:
  --path=<path>
            Some description of what is happening with this path
```

Error:

```
Docopt usage string could not be parsed
--path must not have an argument
```
#### Examples of what does work:

```
Options:
  --path=<path> 
            Some description of what is happening with this path
  --path=<path> [default: somedefault]
            Some description of what is happening with this path
  --path=<path>  Some description of what is happening with this path
```

(for the first working example, note the extra space after `--path=<path>`
#### System:

OS X El Capitan (10.11)

**Comment by jaredgrubb** [comment]
This sounds like the patch being requested in https://github.com/docopt/docopt.cpp/pull/22. Does that seem to match what you are asking?

**Comment by archshift** [comment]
Yes, it would seem so.

**Comment by jaredgrubb** [comment]
I'm going to close this as a dup. Please let me know if you disagree.
