### ISSUE TITLE
Building with gcc 4.8

### ISSUE THREAD

**Issue by Luthaf** [docopt/docopt.cpp#42]
I needed to build docopt using GCC 4.8, because this is default compiler in CentOS 7. 

GCC 4.8 C++11 support is good, but all the `<regex>` functionalities are missing. So I created a fallback to Boost.Regex when building with GCC 4.8, and used C++11 regex in all other cases. 

I used the following diff: 
```diff
diff --git a/docopt.cpp b/docopt.cpp
index 2fd5f42..ce983c5 100644
--- a/docopt.cpp
+++ b/docopt.cpp
@@ -17,9 +17,24 @@
 #include <unordered_map>
 #include <map>
 #include <string>
-#include <regex>
 #include <iostream>
 #include <cassert>
 #include <cstddef>

+#ifdef DOCOPT_USES_BOOST_REGEX
+#include <boost/regex.hpp>
+namespace std {
+	using boost::regex;
+	using boost::sregex_iterator;
+	using boost::smatch;
+	using boost::regex_search;
+	namespace regex_constants {
+		using boost::regex_constants::match_not_null;
+	}
+}
+#else
+#include <regex>
+#endif
```

If you want to include this in docopt, I can do a PR.

**Comment by jaredgrubb** [comment]
Does it work well enough?

**Comment by Luthaf** [comment]
Works well enough for me, with most of the docopt features. I did not ran the test suite, but I can if you are willing to integrate this.

**Comment by jaredgrubb** [comment]
Yes, please do. "Working mostly" is still better than "not at all" but if we advertise that it works, I'd like a little more confidence at least.

**Comment by Luthaf** [comment]
Ok, I only got one failure on the test suite. Please see #43 for the changes.

**Comment by rhd** [comment]
I'd like to see the boost fallback on gcc 4.8 as well.
