### ISSUE TITLE
Undefined reference to docopt::docopt

### ISSUE THREAD

**Issue by peschkaj** [docopt/docopt.cpp#59]
When attempting to build the example code, I get the following compiler error using both g++ (`(Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609`) and clang (3.8.0-2ubuntu4):

```
CMakeFiles/projector.dir/main.cpp.o: In function `main':
/home/jeremiah/src/peschkaj/projector/main.cpp:32: undefined reference to `docopt::docopt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/home/jeremiah/src/peschkaj/projector/main.cpp:38: undefined reference to `docopt::operator<<(std::ostream&, docopt::value const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/projector.dir/build.make:124: recipe for target 'projector' failed
make[2]: *** [projector] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/projector.dir/all' failed
make[1]: *** [CMakeFiles/projector.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

This is on Ubuntu 16.04.1

**Comment by peschkaj** [comment]
Ignore me, I have no idea how to computer

**Comment by nabijaczleweli** [comment]
:D

**Comment by PRESFIL** [comment]
same problem with gcc version 4.9.4 (Ubuntu 4.9.4-2ubuntu1~16.04) + qmake on Linux Mint 18.2
`/home/presfil/Проекты/QtCreator-projects/searcher/src/docopt/main.cpp:29: ошибка: undefined reference to `docopt::docopt(std::string const&, std::vector<std::string, std::allocator<std::string> > const&, bool, std::string const&, bool)'
/home/presfil/Проекты/QtCreator-projects/searcher/src/docopt/main.cpp:32: ошибка: undefined reference to `docopt::operator<<(std::ostream&, docopt::value const&)'
:-1: error: collect2: error: ld returned 1 exit status`

**Comment by jaredgrubb** [comment]
looks like you're not compiling all the files.
