### ISSUE TITLE
Value.asLong not working as expected

### ISSUE THREAD

**Issue by telekenetix** [docopt/docopt.cpp#8]
I don't know if I am missing something, but I can not figure out how to get an integer-type value out from an argument.

From the example, you have an option like this:

``` cpp
--speed=<kn>  Speed in knots [default: 10].
```

Now, if I look at that value after docopt.cpp parsing, I get 

``` cpp
"--speed": "10"
```

You can see that "15" is a string and not an integer.

Calling 

``` cpp
args["--speed"].asLong()
```

results in a runtime exception due to the type being std::string.

Currently, to get around this I'm doing

``` cpp
auto speed = std::stoi(args["--speed"].asString());  // Type of speed will be integer
```

Is there something that needs to be specified in the USAGE string, or is this a bug?

**Comment by jaredgrubb** [comment]
It's hard to know if the output is supposed to be a general string or an integer. The docopt spec uses strings for most arguments, and uses integers for things that count. For example, "[ -v | -vv | -vvv ]" will ive you an integer (1,2,3) for the count.

**Comment by telekenetix** [comment]
What you are saying makes total sense.

Though I would say that when specifying a default value, it should be possible to recognize it as an integer or string value.

**Comment by fsaintjacques** [comment]
I don't agree with the last point, it should not be the help message and parser job to 'guess' the type of an argument. What if the default was "0" but you really just want a name for example?

**Comment by aggsol** [comment]
I agree with @fsaintjacques as if the type of a value of highly application specific. Just imagine a nullable numeric option with a default value of `12` that also can be set as `nil` oder `null`. I recommend to close this issues as won't fix.

**Comment by flying-sheep** [comment]
yeag, `asLong` is really a bad name. should be named `asCount` or something to indicate that it only applies to counted values.

i just encountered exactly the same problem.

**Comment by jaredgrubb** [comment]
I think thats actually a nice idea to change the name.

**Comment by DeanoC** [comment]
An implementation where if the value is representable as a long its held as a long, seems more correct. If a long also passes isString and asString converts it into the string form, it would work in 99% of use cases. That way if you expect a number (and only a number) you can check by calling isLong(), if you expect a string, you check a string by checking isString().
At the moment (and with the purposed changes) its not really useful for numeric arguments, as I have to manually check the format and do the conversion to a number, which is pretty much essential part of a command line parser.

**Comment by taketwo** [comment]
Names `isLong`/`asLong` are very misleading. Given these names (and lack of documentation about how to parse integer parameters) I assumed the following usage pattern:

```cpp
if (!args["--speed"].isLong())
  std::cerr << "--speed argument should be an integer\n";
else
  speed = args["--speed"].asLong();
```

Which, of course, just gave me run-time errors.

**Comment by jaredgrubb** [comment]
Yes, the names are misleading. Anyone have a suggestion?

**Comment by flying-sheep** [comment]
`.count()` or `.asCount()`.

**Comment by fsaintjacques** [comment]
:+1: to @flying-sheep's suggestion

**Comment by jaredgrubb** [comment]
Just FYI we have a patch in discussion if anyone wants to look: https://github.com/docopt/docopt.cpp/pull/28
