### ISSUE TITLE
Ubuntu + g++ 4.9.2 does not pass tests

### ISSUE THREAD

**Issue by tiagomacarios** [docopt/docopt.cpp#9]
Log is here: http://pastie.org/private/djc4ryug6zup7t1xlj7ww
Github markdown messes up the formatting.

**Comment by jrmrjnck** [comment]
I can reproduce the test failures, and it seems like they represent real regressions. 

I'm trying to use docopt.cpp for the first time, and it doesn't seem to understand short/long synonyms nor long option arguments without equal signs.

**Comment by collurio229** [comment]
Changing the regex in Option::parse from
`"(--|-)?(.*?)([,= ]|$)"`
to
 `"(--|-)?([^-].*?)([,= ]+|$)"`
 fixes all but 2 tests for me.

**Comment by hoxnox** [comment]
The same for gentoo and gcc-4.9.2. Created pull-request with fix, suggested by collurio229.

**Comment by jaredgrubb** [comment]
I think this is no longer needed. Please reopen if you disagree.
